### ISSUE TITLE
You get stuck sometimes  and cannot jump

### ISSUE THREAD

**Issue by Xyzyx101** [Xyzyx101/GawkyAdventuresTeamProject#2]

**Comment by SBCopeland** [comment]
Jump bug appears to be fixed, if not please let me know asap.
Jump button changed to Spacebar instead of 'J' key.

**Comment by SBCopeland** [comment]
Took a bit to figure out how to re-open this lol.

So, jump should be working fine now. :)

**Comment by SBCopeland** [comment]
I found an area where this bug happens. So it is still a bug atm. :(
(2nd stage in middle where haystacks are. Try to jump up on them in certain areas.)

**Comment by mak1ca** [comment]
The bug happens when you go in the 2nd barn and climb the hay stacks. Just found it :)

(P.S. Ya Steve that's the one I spotted as well)

**Comment by SBCopeland** [comment]
Cleaned up Player Class.
Created initPlayer to handle default player settings.
Created setPlayerModel to handle model create and bounding box setup for it.
The two created functions replaced all that just being in the constructor.

Bug shouldn't happen on the original stage.
Bug can happen anywhere on 2nd level - where the tractors are.

commit ca4127535ad5ae5fc5378ac14c41a41d1aaa4d85

**Comment by mak1ca** [comment]
Gawky still can't jump sometimes in the first area as well. When you go under a ledge, and jump, he will not jump and vibrate again.
